package com.demo;

import org.apache.log4j.Logger;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kangkang' at '17-1-23 下午8:53' with Gradle 2.14
 *
 * @author kangkang, @date 17-1-23 下午8:53
 */
public class Library {

	private static final Logger logger = Logger.getLogger(Library.class);

    public static void main(String args[]){
		say();
    }
    
    public static void say(){

    	try {
			if(1==1){
				throw new NullPointerException("------空指针异常");
			}
		}catch (Exception e){
			System.out.println("------");
		}
		System.out.println("------猩球崛起!");


    }
}
