package com.demo;
import com.demo.Library;
import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'kangkang' at '17-1-23 下午8:53' with Gradle 2.14
 *
 * @author kangkang, @date 17-1-23 下午8:53
 */
public class LibraryTest {

    @Test
    public void testSomeLibraryMethod() {
        Library.say();
    }

}
